pipeline {
    agent {
        docker {
            image 'node:alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {        
        stage('Build') {
            steps {
                dir('simple-node-js-react-npm-app') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('simple-node-js-react-npm-app') {
                    sh './jenkins/scripts/test.sh'
                }
            }
        }
        stage('Deliver') {
            steps {
                dir('simple-node-js-react-npm-app') {
                    sh './jenkins/scripts/deliver.sh'
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    sh './jenkins/scripts/kill.sh'
                }
            }
        }        
    }
}
